name: Laravel CI

on:
  push:
    branches: [ "breeze-setup" ]
  pull_request:
    branches: [ "breeze-setup" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, mysql, pdo_mysql, tokenizer, ctype, json, bcmath, openssl

      - name: Install Node.js (for Vite build)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets (Vite)
        run: npm run build

      - name: Generate Laravel APP key
        run: php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run database migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: laravel_user
          DB_PASSWORD: password
        run: |
          php artisan config:clear
          php artisan migrate:fresh --env=testing

      - name: Run Laravel Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_test
          DB_USERNAME: laravel_user
          DB_PASSWORD: password
          APP_ENV: testing
        run: php artisan test
